CREATE TABLE [dbo].[ADDR_OBJ_DIVISION] (
    [ID]       BIGINT NOT NULL,
    [PARENTID] BIGINT NOT NULL,
    [CHILDID]  BIGINT NOT NULL,
    [CHANGEID] BIGINT NOT NULL,
    CONSTRAINT [PK_ADDR_OBJ_DIVISION] PRIMARY KEY CLUSTERED ([ID] ASC)
);



