CREATE TABLE [dbo].[CHANGE_HISTORY] (
    [CHANGEID]    BIGINT        NOT NULL,
    [OBJECTID]    BIGINT        NOT NULL,
    [ADROBJECTID] VARCHAR (MAX) NOT NULL,
    [OPERTYPEID]  BIGINT        NOT NULL,
    [NDOCID]      BIGINT        NULL,
    [CHANGEDATE]  DATETIME      NOT NULL
);

