CREATE TABLE [dbo].[NORMATIVE_DOCS_TYPES] (
    [ID]        BIGINT        NOT NULL,
    [NAME]      VARCHAR (500) NOT NULL,
    [STARTDATE] DATETIME      NOT NULL,
    [ENDDATE]   DATETIME      NOT NULL,
    CONSTRAINT [PK_NORMATIVE_DOCS_TYPES] PRIMARY KEY CLUSTERED ([ID] ASC)
);



