CREATE TABLE [dbo].[OBJECT_LEVELS] (
    [LEVEL]      BIGINT        NOT NULL,
    [NAME]       VARCHAR (250) NOT NULL,
    [SHORTNAME]  VARCHAR (50)  NULL,
    [UPDATEDATE] DATETIME      NOT NULL,
    [STARTDATE]  DATETIME      NOT NULL,
    [ENDDATE]    DATETIME      NOT NULL,
    [ISACTIVE]   BIT           NOT NULL
);

