CREATE TABLE [dbo].[REESTR_OBJECTS] (
    [OBJECTID]   BIGINT        NOT NULL,
    [CREATEDATE] DATETIME      NOT NULL,
    [CHANGEID]   BIGINT        NOT NULL,
    [LEVELID]    BIGINT        NOT NULL,
    [UPDATEDATE] DATETIME      NOT NULL,
    [OBJECTGUID] VARCHAR (MAX) NOT NULL,
    [ISACTIVE]   BIT           NOT NULL
);

