'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Этот исходный код был создан с помощью xsd, версия=4.7.3081.0.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.v8.1c.ru/ssl/AddressSystem"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.v8.1c.ru/ssl/AddressSystem", IsNullable:=false)>  _
Partial Public Class AddressStatuses
    
    Private addressStatusField() As AddressStatusesAddressStatus
    
    Private versionField As String
    
    Private updateDateField As String
    
    Private regionField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("AddressStatus")>  _
    Public Property AddressStatus() As AddressStatusesAddressStatus()
        Get
            Return Me.addressStatusField
        End Get
        Set
            Me.addressStatusField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Version() As String
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property UpdateDate() As String
        Get
            Return Me.updateDateField
        End Get
        Set
            Me.updateDateField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Region() As String
        Get
            Return Me.regionField
        End Get
        Set
            Me.regionField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.v8.1c.ru/ssl/AddressSystem")>
Partial Public Class AddressStatusesAddressStatus

	Private tYPEField As String

	Private idField As String

	Private kEYField As String

	Private vALUEField As String

	'''<remarks/>
	<System.Xml.Serialization.XmlAttributeAttribute()>
	Public Property TYPE() As String
		Get
			Return Me.tYPEField
		End Get
		Set
			Me.tYPEField = value
		End Set
	End Property

	'''<remarks/>
	<System.Xml.Serialization.XmlAttributeAttribute()>
	Public Property ID() As String
		Get
			Return Me.idField
		End Get
		Set
			Me.idField = value
		End Set
	End Property

	'''<remarks/>
	<System.Xml.Serialization.XmlAttributeAttribute()>
	Public Property KEY() As String
		Get
			Return Me.kEYField
		End Get
		Set
			Me.kEYField = value
		End Set
	End Property

	'''<remarks/>
	<System.Xml.Serialization.XmlAttributeAttribute()>
	Public Property VALUE() As String
		Get
			Return Me.vALUEField
		End Get
		Set
			Me.vALUEField = value
		End Set
	End Property
End Class
