'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Этот исходный код был создан с помощью xsd, версия=4.7.3081.0.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.v8.1c.ru/ssl/AddressSystem"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.v8.1c.ru/ssl/AddressSystem", IsNullable:=false)>  _
Partial Public Class Steads
    
    Private steadField() As SteadsStead
    
    Private versionField As String
    
    Private updateDateField As String
    
    Private regionField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Stead")>  _
    Public Property Stead() As SteadsStead()
        Get
            Return Me.steadField
        End Get
        Set
            Me.steadField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Version() As String
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property UpdateDate() As String
        Get
            Return Me.updateDateField
        End Get
        Set
            Me.updateDateField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Region() As String
        Get
            Return Me.regionField
        End Get
        Set
            Me.regionField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.v8.1c.ru/ssl/AddressSystem")>  _
Partial Public Class SteadsStead
    
    Private pARENTGUIDField As String
    
    Private eXTRAGUIDField As String
    
    Private nUMBERField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property PARENTGUID() As String
        Get
            Return Me.pARENTGUIDField
        End Get
        Set
            Me.pARENTGUIDField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property EXTRAGUID() As String
        Get
            Return Me.eXTRAGUIDField
        End Get
        Set
            Me.eXTRAGUIDField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property NUMBER() As String
        Get
            Return Me.nUMBERField
        End Get
        Set
            Me.nUMBERField = value
        End Set
    End Property
End Class